name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (Installer)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./INSTALLER.gf
          asset_name: INSTALLER.gf
          asset_content_type: text/plain

      - name: Upload Release Asset (Manual)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GPTFlow_Manual.md
          asset_name: GPTFlow_Manual.md
          asset_content_type: text/markdown
