name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract Release Notes from CHANGELOG.md
      - name: Generate Release Notes
        id: generate_notes
        run: |
          version="${GITHUB_REF##*/}" # Extract the tag name
          echo "Extracting release notes for version $version"
          awk "/^## $version/,/^## /{if (\$0 !~ /^## $version/) print}" CHANGELOG.md | sed '$d' > RELEASE_NOTES.md
          echo "Release notes:"
          cat RELEASE_NOTES.md

      # Step 3: Create a GitHub Release and upload assets
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          files: |
            ./INSTALLER.gf
            ./GPTFlow_Manual.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}